### ISSUE TITLE
[@mlx/parser] Return all routes of an Angular app

### ISSUE THREAD

**Issue by chrisguttandin** [mgechev/smarty#1]
Hi @mgechev,

while I was reading you’re article about the machine learning driven approach to bundling, I realized that I could probably use your parser to retrieve all routes of an Angular app. I want to use the list of routes to generate a static version on an Angular app. Unfortunately I realized that you’re implementation only returns the root route for each lazily loaded group of routes. I know that that’s all you need to know to get the entry points for the chunks, but it’s not enough information for my use case. Would you be interested in a pull request that introduces an option to include all routes?

I'm thinking of a function signature like this:

```typescript
export enum RouteType {
    All,
    Lazy
}

parseRoutes (tsconfig: string, projectType: ProjectType, routeType: RouteType = RouteType.Lazy);
```

Or do you think it’s better when I fork your project and create a separate parser for that use case? One argument for doing so is that I have no idea about how to provide similar functionality for React apps.

**Comment by mgechev** [comment]
Hey @chrisguttandin! The parser should return all the routes, if it doesn't it's an issue. Did you try it on your application? Could you provide a minimal demo so I can test and fix the problem?

**Comment by chrisguttandin** [comment]
Hi @mgechev, sorry for the late reply. Yes I tried it on one of my applications. I usually try out new things with one of my slide decks because they are super simple Angular apps. This is the repo that I used: https://github.com/chrisguttandin/web-audio-conference-2016.

I ran into a problem when I tried out the parser. I'm using the CLI to scaffold my app and the CLI creates separate modules for the routes. That means that my routes won't be defined inside of the `AppModule`. The CLI will create a separate `AppRoutingModule` instead. I just modified the parser's source code to look for the `AppRoutingModule` instead of the `AppModule` as a starting point. That might have broken something else.

The behavior of the CLI is described here: https://github.com/angular/angular-cli/blob/master/docs/documentation/stories/routing.md

If you want to create an minimal app with an `AppRoutingModule` you can create one by running `npx @angular/cli new example --routing`.

Does that help to track down the problem or do you want me to create a full example app?

**Comment by mgechev** [comment]
Thanks! I will look into that next week.

**Comment by mgechev** [comment]
@chrisguttandin fixed the issue. Soon, you should get access to it as well.
